### ISSUE TITLE
asciinema recording format support

### ISSUE THREAD

**Issue by tg123** [tg123/sshpiper#222]

**Comment by clysto** [comment]
This commit introduces two major changes:

1. **Log Path Adjustment:**
   - The previous PR changes have been reverted, and now we use `uniqueID` as the location for logs. This approach is more efficient because `uniqueID` is already widely used in plugins, making it a better choice for log storage. Additionally, using `uniqueID` allows plugins to easily retrieve the log storage location, enabling them to perform further actions, such as uploading logs to cloud storage or databases after a session ends. This flexibility was not possible with the previous approach, which used a combination of `username + timestamp` for log storage.

2. **Asciicast v2 Format Support:**
   - Added support for **asciicast v2** format, which can be enabled through the command-line parameter `--asciicast-log-dir`. Once enabled, terminal sessions will be recorded in asciicast v2 format and stored in the specified directory.
   - `asciicast` is a JSON-based format used for recording terminal sessions. The v2 version provides a structured format that's easy to parse and integrate. Detailed information about the asciicast v2 format can be found [here](https://docs.asciinema.org/manual/asciicast/v2).

   **Playing Recorded Sessions**:
   You can use the **asciinema** CLI tool to play the recorded `.cast` files:
   ```bash
   asciinema play /path/to/shell.cast
   ```
   This will replay the terminal session in real-time.

   **Web Integration**:
   Asciinema also provides a web player, making it convenient for plugin developers to embed terminal session recordings into web pages. This makes it easier to debug or showcase terminal interactions, enhancing usability.

   This feature resolves **issue #222**, fulfilling the need for a standardized session recording format that can be easily integrated into web interfaces.
