### ISSUE TITLE
Mapping features for database upstream driver

### ISSUE THREAD

**Issue by Sea-you** [tg123/sshpiper#62]
Looks like this feature has been implemented in the YAML upstream driver, but not in others. I'm especially interested in using the feature with the database driver as it'd definitely scale better than Yaml. 

Do you have any plans to implement this in the database driver in the near future?

**Comment by tg123** [comment]
PR is welcomed, I planned a standalone and flexible driver but I do not have time at the moment :(

**Comment by ironashram** [comment]
@tg123 
i've been working on the implementation of the missing mapping features for the database driver
you can see the diff with my fork here, https://github.com/tg123/sshpiper/compare/master...ironashram:master

i basically took inspiration from the yaml driver and made a few adjustments, still there may be work to do.
i'm writing to eventually start a discussion, will this be something you would be interested in merging? We are thinking of using this in the near future but the missing mapping function for the database driver is something we need
If you have suggestions, comments on the above code feel free to share, i'm willing to work on this in order to make it suitable to be merged
